# Generated by Django 3.2.7 on 2021-09-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_knot_dtcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knot',
            name='dtcode',
            field=models.CharField(max_length=128),
        ),
    ]
